### ISSUE TITLE
Project maintainership

### ISSUE THREAD

**Issue by adisbladis** [nix-community/tree-sitter-nix#47]
The maintenance of tree-sitter-nix is not active enough, and important fixes are not being merged.

An example of this is https://github.com/nix-community/tree-sitter-nix/pull/38 which has been open since June with me pinging @cstrahan a little bit over a month ago with no response.

Therefore I would like to add to be added as an additional maintainer.
I don't intend to hack very actively on tree-sitter-nix, but I am intending to merge PRs and cut releases.

**Comment by zowoq** [comment]
https://github.com/orgs/nix-community/discussions/469

Based on the discussion when it was transferred I don't see a problem with having additional maintainers.

**Comment by Mic92** [comment]
Sounds good to me.

**Comment by cstrahan** [comment]
> The maintenance of tree-sitter-nix is not active enough, and important fixes are not being merged.

As the original author and current "maintainer" (more in name than in spirit, regrettably), I 100% agree.

> Therefore I would like to add to be added as an additional maintainer.

Also agree here, and I thank you for being willing to pick up the slack I've left. I migrated this repo here because I didn't want this work to wither on the vine, so I'm all for additional maintainers. If I could figure out how to make you a maintainer, I'd do that myself (my settings tab here on GH is pretty sparse -- dunno if it's a permissions thing or ignorance on my part).

I genuinely wish I could be more active but, as life is at the moment, I don't have enough time to so much as glance at these activity notifications 😞.
